# Generated by Django 4.2.27 on 2026-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ETLRun",
            fields=[
                ("run_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=64)),
                ("job_name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("rows_extracted", models.IntegerField(default=0)),
                ("rows_loaded", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "etl_runs",
                "indexes": [
                    models.Index(fields=["status"], name="etl_runs_status_1f650e_idx"),
                    models.Index(
                        fields=["job_name"], name="etl_runs_job_nam_6ecbc7_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="etl_runs_started_41a31e_idx"
                    ),
                ],
            },
        ),
    ]
