# Generated by Django 4.2.27 on 2026-01-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimCustomer",
            fields=[
                (
                    "customer_key",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("customer_id", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("country", models.CharField(blank=True, max_length=64, null=True)),
                ("city", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "dim_customers",
            },
        ),
        migrations.CreateModel(
            name="DimProduct",
            fields=[
                ("product_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dim_products",
            },
        ),
        migrations.CreateModel(
            name="DimTime",
            fields=[
                ("time_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("week", models.IntegerField()),
            ],
            options={
                "db_table": "dim_time",
            },
        ),
        migrations.CreateModel(
            name="FactOrder",
            fields=[
                ("order_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_id", models.CharField(max_length=64, unique=True)),
                ("order_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analytics.dimcustomer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analytics.dimproduct",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        db_column="time_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analytics.dimtime",
                    ),
                ),
            ],
            options={
                "db_table": "fact_orders",
            },
        ),
        migrations.AddIndex(
            model_name="dimtime",
            index=models.Index(fields=["date"], name="dim_time_date_7fd609_idx"),
        ),
        migrations.AddIndex(
            model_name="dimtime",
            index=models.Index(
                fields=["year", "month"], name="dim_time_year_25666c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dimproduct",
            index=models.Index(
                fields=["product_id"], name="dim_product_product_f1e30c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dimproduct",
            index=models.Index(
                fields=["category"], name="dim_product_categor_0a026a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dimcustomer",
            index=models.Index(
                fields=["customer_id"], name="dim_custome_custome_b209da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dimcustomer",
            index=models.Index(
                fields=["country"], name="dim_custome_country_db18a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorder",
            index=models.Index(
                fields=["created_at"], name="fact_orders_created_2a4b26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorder",
            index=models.Index(
                fields=["customer"], name="fact_orders_custome_2afd7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorder",
            index=models.Index(fields=["time"], name="fact_orders_time_ke_87673b_idx"),
        ),
    ]
